In [5]:
# pip install pandas
import pandas as pd

sales_data = pd.read_csv(
     r"C:\Users\Shree\Desktop\Data_Science\Data_practice\Libraries\Visualization\Matplotlib\Datasets\sales_record\1000 Sales Records.csv"
)

sales_data.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45

In [9]:
# check with missing val,info etc
sales_data.info()
sales_data.count()
sales_data.describe()

# with above there is no empty data we can move further

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          1000 non-null   object
 1   Country         1000 non-null   object
 2   Item Type       1000 non-null   object
 3   Sales Channel   1000 non-null   object
 4   Order Priority  1000 non-null   object
 5   Order Date      1000 non-null   object
 6   Order ID        1000 non-null   int64
 7   Ship Date       1000 non-null   object
 8   Units Sold      1000 non-null   int64
 9   Unit Price      1000 non-null   float64
 10  Unit Cost       1000 non-null   float64
 11  Total Revenue   1000 non-null   float64
 12  Total Cost      1000 non-null   float64
 13  Total Profit    1000 non-null   float64
dtypes: float64(5), int64(2), object(7)
memory usage: 109.5+ KB

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+03,1000.000000,1000.00000,1000.000000,1.000000e+03,1.000000e+03,1.000000e+03
mean,5.496813e+08,5053.988000,262.10684,184.965110,1.327322e+06,9.361192e+05,3.912026e+05
std,2.571334e+08,2901.375317,216.02106,175.289311,1.486515e+06,1.162571e+06,3.836402e+05
min,1.029280e+08,13.000000,9.33000,6.920000,2.043250e+03,1.416750e+03,5.326100e+02
25%,3.280740e+08,2420.250000,81.73000,56.670000,2.811919e+05,1.649319e+05,9.837612e+04
50%,5.566097e+08,5184.000000,154.06000,97.440000,7.549392e+05,4.647261e+05,2.772260e+05
75%,7.696945e+08,7536.750000,421.89000,263.330000,1.733503e+06,1.141750e+06,5.484568e+05
max,9.955298e+08,9998.000000,668.27000,524.960000,6.617210e+06,5.204978e+06,1.726181e+06

In [33]:
# check with total revenue = unit sold * unit 
# .isclose() method checks whether two values are close to each other, or not. Returns True if the values are close, otherwise False.
import numpy as np
sales_data['Expected_revnue'] = sales_data['Units Sold'] * sales_data['Unit Price']
sales_data['revenue_matched'] = np.isclose(
    sales_data['Total Revenue'],
    sales_data['Expected_revnue']
)

# checked with if any no mathced revnue data
mismath_revnue = sales_data[~sales_data['revenue_matched']]
mismath_revnue

# check with expected profit = total revnue - total cost

sales_data['expected_profit'] = sales_data['Total Revenue'] - sales_data['Total Cost']
sales_data['Profit_matched'] = np.isclose(
    sales_data['Total Profit'],
    sales_data['expected_profit']
)

mismath_profit = sales_data[~sales_data['Profit_matched']]
mismath_profit

Empty DataFrame
Columns: [Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit, Delivary days, Month, Expected_revnue, revenue_matched, expected_profit, Profit_matched]
Index: []

In [ ]:
# data understanding and cleaning
# 1. covert date 
sales_data['Order Date'] = pd.to_datetime(sales_data['Order Date'])
sales_data['Ship Date'] = pd.to_datetime(sales_data['Ship Date'])

# 2. create useful features
sales_data['Delivary days'] = (sales_data['Ship Date']-sales_data['Order Date']).dt.days
sales_data['Month'] = (sales_data['Order Date']).dt.month
sales_data['Year'] = (sales_data['Order Date']).dt.year

# deleted the col
# sales_data.drop(columns=['Dilivary days'], inplace=True)
sales_data

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,...,Total Revenue,Total Cost,Total Profit,Delivary days,Month,Expected_revnue,revenue_matched,expected_profit,Profit_matched,Year
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,2014-10-18,686800706,2014-10-31,8446,437.20,...,3692591.20,2224085.18,1468506.02,13,10,3692591.20,True,1468506.02,True,2014
1,North America,Canada,Vegetables,Online,M,2011-11-07,185941302,2011-12-08,3018,154.06,...,464953.08,274426.74,190526.34,31,11,464953.08,True,190526.34,True,2011
2,Middle East and North Africa,Libya,Baby Food,Offline,C,2016-10-31,246222341,2016-12-09,1517,255.28,...,387259.76,241840.14,145419.62,39,10,387259.76,True,145419.62,True,2016
3,Asia,Japan,Cereal,Offline,C,2010-04-10,161442649,2010-05-12,3322,205.70,...,683335.40,389039.42,294295.98,32,4,683335.40,True,294295.98,True,2010
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,2011-08-16,645713555,2011-08-31,9845,9.33,...,91853.85,68127.40,23726.45,15,8,91853.85,True,23726.45,True,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Middle East and North Africa,Azerbaijan,Snacks,Offline,C,2010-04-18,534085166,2010-04-25,6524,152.58,...,995431.92,635698.56,359733.36,7,4,995431.92,True,359733.36,True,2010
996,Europe,Georgia,Baby Food,Offline,H,2011-08-01,590768182,2011-09-07,288,255.28,...,73520.64,45912.96,27607.68,37,8,73520.64,True,27607.68,True,2011
997,Middle East and North Africa,United Arab Emirates,Vegetables,Online,C,2011-05-12,524363124,2011-06-28,9556,154.06,...,1472197.36,868927.08,603270.28,47,5,1472197.36,True,603270.28,True,2011
998,Europe,Finland,Household,Offline,L,2016-01-25,289606320,2016-02-14,9801,668.27,...,6549714.27,4925394.54,1624319.73,20,1,6549714.27,True,1624319.73,True,2016
999,Europe,Portugal,Cereal,Offline,C,2014-04-10,811546599,2014-05-08,3528,205.70,...,725709.60,413164.08,312545.52,28,4,725709.60,True,312545.52,True,2014