In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("dataset/titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [6]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [19]:
target = df.Survived
inputs = df.drop('Survived',axis='columns')

In [20]:
# manage sex feature 
dummy = pd.get_dummies(inputs['Sex']).astype(int)
dummy

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [21]:
inputs = pd.concat([inputs,dummy],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [22]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [23]:
# check if na value is there or not
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [24]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [26]:
# we have nan value in age, replacing it with mean of that column

inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

   Pclass        Age     Fare  female
0       3  22.000000   7.2500       0
1       1  38.000000  71.2833       1
2       3  26.000000   7.9250       1
3       1  35.000000  53.1000       1
4       3  35.000000   8.0500       0
5       3  29.699118   8.4583       0
6       1  54.000000  51.8625       0
7       3   2.000000  21.0750       0
8       3  27.000000  11.1333       1
9       2  14.000000  30.0708       1

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [29]:
# using Guassian Naive bayes - used when data distribution normal
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [30]:
model.fit(x_train,y_train)

GaussianNB()

In [31]:
model.score(x_test,y_test)

0.7597765363128491

In [32]:
y_test[:10]

163    0
413    0
231    0
494    0
724    1
626    0
683    0
56     1
360    0
26     0
Name: Survived, dtype: int64

In [33]:
model.predict(x_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [34]:
model.predict_proba(x_test[:10])

array([[0.95864949, 0.04135051],
       [0.9261784 , 0.0738216 ],
       [0.96724622, 0.03275378],
       [0.9622702 , 0.0377298 ],
       [0.6361791 , 0.3638209 ],
       [0.9316296 , 0.0683704 ],
       [0.93193907, 0.06806093],
       [0.22455046, 0.77544954],
       [0.9684848 , 0.0315152 ],
       [0.96744743, 0.03255257]])